# Generated by Django 5.0.4 on 2024-05-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="last_login",
        ),
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[("Admin", "admin"), ("Regular", "regular"), ("Anon", "anon")],
                default="regular",
                max_length=10,
            ),
        ),
    ]
